/** Deterministic router task categories. */
export enum TaskType {
  // -> code model (Qwen)
  IMPLEMENT = "IMPLEMENT",
  EDIT = "EDIT",
  GENERATE = "GENERATE",
  PARSE = "PARSE",
  PLAN = "PLAN",
  // -> debug model (DeepSeek)
  CI_ANALYSIS = "CI_ANALYSIS",
  DEBUG = "DEBUG",
  REASONING = "REASONING",
}

/** Per-issue job lifecycle states (persisted). */
export enum JobState {
  QUEUED = "QUEUED",
  PARSING = "PARSING",
  PLANNING = "PLANNING",
  IMPLEMENTING = "IMPLEMENTING",
  PR_OPEN = "PR_OPEN",
  CI_RUNNING = "CI_RUNNING",
  FIXING = "FIXING",
  MERGED = "MERGED",
  DEPLOYED = "DEPLOYED",
  FAILED = "FAILED",
}

export const TERMINAL_STATES: ReadonlySet<JobState> = new Set([
  JobState.MERGED,
  JobState.DEPLOYED,
  JobState.FAILED,
]);

export interface IssueJob {
  id: number;
  owner: string;
  repo: string;
  issueNumber: number;
  title: string;
  branch: string | null;
  prNumber: number | null;
  headSha: string | null;
  state: JobState;
  retryCount: number;
  pro: boolean;
  lastError: string | null;
  spec: string | null; // JSON string of IssueSpec
  plan: string | null; // JSON string of string[]
  progressCommentId: number | null;
  progressPrCommentId: number | null;
  epic: boolean;
  /** Whether CI exists for the current head SHA: null = undetermined, true/false once checked. */
  ciPresent: boolean | null;
  createdAt: string;
  updatedAt: string;
}

/** Structured spec extracted from a GitHub issue. */
export interface IssueSpec {
  title: string;
  summary: string;
  requirements: string[];
  acceptanceCriteria: string[];
  affectedAreas: string[];
  notes: string;
  /** The original issue title + body, verbatim. Source of truth for the implementer. */
  originalRequest?: string;
}

/** A single file mutation proposed by the code model. */
export interface FileEdit {
  path: string;
  action: "create" | "modify" | "delete" | "edit";
  /** Full file content for create/modify/delete (delete = ""). Unused for "edit". */
  content: string;
  /** For action "edit": exact existing text to find. */
  search?: string;
  /** For action "edit": replacement text. */
  replace?: string;
}

export interface ImplementResult {
  commitMessage: string;
  summary: string;
  files: FileEdit[];
}

export interface DebugResult {
  rootCause: string;
  fixInstructions: string;
  suspectedFiles: string[];
}

export interface CiOutcome {
  conclusion: "success" | "failure" | "neutral" | "cancelled" | "timed_out" | "unknown";
  runId: number | null;
  headSha: string;
  logsExcerpt: string;
}

// ---------------------------------------------------------------------------
// Project Mode
// ---------------------------------------------------------------------------

/** Lifecycle states for a project (multi-task orchestration). */
export enum ProjectState {
  PLANNING = "PLANNING",
  AWAITING_APPROVAL = "AWAITING_APPROVAL",
  RUNNING = "RUNNING",
  PAUSED = "PAUSED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",
}

export const PROJECT_TERMINAL_STATES: ReadonlySet<ProjectState> = new Set([
  ProjectState.COMPLETED,
  ProjectState.CANCELLED,
  ProjectState.FAILED,
]);

/** Lifecycle states for individual project tasks. */
export enum ProjectTaskState {
  PENDING = "PENDING",
  BLOCKED = "BLOCKED",
  READY = "READY",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED",
}

export const PROJECT_TASK_TERMINAL_STATES: ReadonlySet<ProjectTaskState> = new Set([
  ProjectTaskState.COMPLETED,
  ProjectTaskState.FAILED,
  ProjectTaskState.SKIPPED,
]);

/** A project record (multi-issue orchestration). */
export interface Project {
  id: number;
  owner: string;
  repo: string;
  issueNumber: number;
  title: string;
  state: ProjectState;
  statusCommentId: number | null;
  plan: string | null;
  createdBy: string;
  lastError: string | null;
  createdAt: string;
  updatedAt: string;
}

/** A single task within a project, managed by Task Master. */
export interface ProjectTask {
  id: number;
  projectId: number;
  taskIndex: number;
  title: string;
  description: string;
  state: ProjectTaskState;
  dependencies: string | null;
  subtasks: string | null;
  jobId: number | null;
  lastError: string | null;
  branch: string | null;
  prNumber: number | null;
  headSha: string | null;
  retryCount: number;
  ciRetryCount: number;
  worktreePath: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Task plan generated by the LLM (Task Master output). */
export interface TaskPlan {
  tasks: TaskPlanEntry[];
}

export interface TaskPlanEntry {
  title: string;
  description: string;
  dependencies: number[];
  subtasks: string[];
}

/** Interface for a future task executor. */
export interface TaskExecutor {
  executeTask(project: Project, task: ProjectTask): Promise<void>;
  canExecute(task: ProjectTask): boolean;
}

// ---------------------------------------------------------------------------
// Phase Mode (Epic Planner)
// ---------------------------------------------------------------------------

/** Lifecycle states for project phases. */
export enum PhaseState {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED",
}

/** A phase within a phased (epic) project. */
export interface ProjectPhase {
  id: number;
  projectId: number;
  phaseIndex: number;
  title: string;
  description: string;
  state: PhaseState;
  createdAt: string;
  updatedAt: string;
}

/** Supported project commands from issue comments. */
export type ProjectCommand =
  | { type: "approve" }
  | { type: "pause" }
  | { type: "resume" }
  | { type: "status" }
  | { type: "retry"; taskId: number }
  | { type: "cancel" };
